#!/bin/bash

# clean existing distribution if any

___here=$(dirname `readlink -f $0`)

source "$___here/configurations.sh"

echo
if [ -d "$___here/$___wlcBashScriptsBuildingOutputFolderName" ]; then
    echo
    echo -e  `colorful  $VE_line_60  textRed`


    rm -rf "$___here/$___wlcBashScriptsBuildingOutputFolderName"
    echo -en `colorful  "Deleted: "  textRed`
    echo -en '<this repository>/'
    echo -e  `colorful  "$___wlcBashScriptsBuildingOutputFolderName" textRed`


    rm `find "$___here/$___wlcBashScriptsSourceLibFolderName/" -name "*.filled-template"`
    echo -en `colorful  "Deleted: "  textRed`
    echo -en '<this repository>/'
    echo -e  `colorful  "$___wlcBashScriptsSourceLibFolderName"      textRed`


    echo -e  `colorful  $VE_line_60  textRed`
    echo
    echo
fi
echo