#!/bin/bash

# clean existing distribution if any

___here=$(dirname `readlink -f $0`)

source "$___here/configurations.sh"

echo ''
if [ -d "$___here/$___wlcBashScriptsBuildingOutputFolderName" ]; then
    rm -rf "$___here/$___wlcBashScriptsBuildingOutputFolderName"
    echo -e '\e[33m────────────────────────────────────────────────────────────\e[0;0m'
    echo -e "\e[33mREMOVED: \e[31m$___here/$___wlcBashScriptsBuildingOutputFolderName\e[0;0m"
    echo -e '\e[33m────────────────────────────────────────────────────────────\e[0;0m'
fi
