#!/bin/bash

___here=$(dirname `readlink -f $0`)

source "$___here/building-tools/print-repository-location.sh"
source "$___here/building-tools/_configurations.sh"
source "$___here/building-tools/make.sh"
source "$___here/building-tools/install-local-machine-package.sh"

unset ___here