#!/bin/bash

___here=$(dirname `readlink -f $0`)
___senariosToBuild=`ls $___here/senario-specific-configurations`


source "$___here/building-tools/_utilities/ansi-colors.sh"
source "$___here/configurations.sh"
source "$___here/building-tools/print-repository-location.sh"
source "$___here/building-tools/1-make-packages/make-for-organization-unnamed.sh" $*
source "$___here/building-tools/2-installation/install-on-local-machine.sh"     $*


unset ___senariosToBuild
unset ___here