#!/bin/bash

function ___install-wlc-bash-srcipts {
    local basePath="$1"
    local sourceItemName
    local sourceItemPath
    local targetFolderPath

    local deploymentTargetLocation="$HOME"

    if [ "$basePath" == "$HOME" ]; then
        echo -e "Source files are already in ~."
        echo -e "Nothing to do."
        return
    fi

    local VE_line='──────────────────────────────────────────────────'

    echo    $VE_line
    echo -e "Deploying from \"\e[34m$basePath\e[0;0m\""
    echo    $VE_line

    for sourceItemName in `ls -A $basePath`; do
        sourceItemPath="$basePath/$sourceItemName"

        # 如果遇到文件，则直接复制，-f 强迫覆盖旧有文件。
        if [    -f "$sourceItemPath" ]; then
            if [ "$sourceItemName" == 'install' ]; then
                echo -e "SKIPPED: $sourceItemName"
                continue
            fi

            cp  -f "$sourceItemPath"   "$deploymentTargetLocation/"
            echo -e "FILE:    \e[31m$sourceItemName\e[0;0m"
        fi


        # 如果遇到文件夹，则先删除可能存在的旧目标文件夹，而后复制整个源文件夹。
        if [    -d "$sourceItemPath" ]; then
            targetFolderPath="$deploymentTargetLocation/$sourceItemName"

            if [    -d "$targetFolderPath" ]; then
                rm -rf "$targetFolderPath"
            fi

            cp -rf "$sourceItemPath"   "$deploymentTargetLocation/"
            echo -e "FOLDER:  \e[32m$sourceItemName\e[0;0m"
        fi
    done

    unset -f ___install-wlc-bash-srcipts

    echo    $VE_line
    echo -e "DONE"
    echo    $VE_line

    echo -n 'Press any key to continue '
    read -s -n 1
    exec bash -l
}



___here=$(dirname `readlink -f $0`) # 获取当前运行的文件夹
___install-wlc-bash-srcipts   "$___here"
unset ___here
